apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: cluster-otlp-teste-4-location
  description: Location to import all cluster-otlp-teste-4 catalog components
spec:
  targets:
    - ./.platform/*.yaml
